import express from "express";
import { GoogleSpreadsheet } from "google-spreadsheet";
import { JWT } from "google-auth-library";

import dotenv from "dotenv";

dotenv.config();
const app = express();

// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: "digital-labs-service@craftdigitallabs.iam.gserviceaccount.com",
  key: "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQDi+cWNoTibQ3rQ\n+uMX+UWex1KURTjk2nk3XHnGJwVJge250ldPzyYWHqEgVBByqxUzM8c0Jw8cKPty\niZzhYleB3czxJCPSip5BbEyNUehyQgGkFclwG7lRFq6TVHMQWvkDmfcACP4HMdE0\nnoKa90JYH2Gin1jplqDDQF3dPIfLzRARWK7Fom6PvcDv/NplEeSr0yBMvSD5wYAr\nnDfGZmHVLajgabByXwGMtcqqXFqqEXRKO3OY+p3sCCWOFgtZ575A2LUfNb+MqgDZ\n+rXYl9UH5UKB1wKlVe1hEkXivSH64RIvAHmst+WjaSk3RwvedHfJ11bn8bqNarYT\nt4ZfuVL9AgMBAAECggEAFS+K0jHytoIBbuEux5g+Tdg9VoFG6AxBFTrzU4dlNcZu\nuedZZqXSCxgtIkyGboBBOH1u7L4alHPPfeeSC52Mx8k8Aw7EWIy/bHbfMa+sBSzb\nugTzP5zEMD6a6T3lhujJkR2oEZ+alRxVcoEQdXDP3KmCiQCGTDisOnKscDqL/aiH\nfjDkIpRL3qZFoXFissWxfzHLKFLI15/qVp3F+rlJ1Y/eEGjjMK5evXwWJJ/m4k7t\nQHKvHQWYYxC1kBz2fo3ULDLCcsBoNANE1tN3V5V2flbt8Xp3kM2YeV4SJDThps+o\naW1R46v2Wywi9NHdcN0yN89UaX42iDkNTU48WNVaNwKBgQD5rXOkrsQ+6kUCWeNP\n2vQKj3CN+3xsCqKxWklfxisMZ6XYx7Q+hgFgGEFfVOV5z4nFlaQ/7VKkfdOm7mCn\nCF4iBHNefZ+aWXasUkSp21m9UChRSsUtYdAX6bOq4xGB+fm4yAyayeDICPwBScpA\nRemvjlv/O0MW0D2QCV/7jJhQUwKBgQDouSdgyBwx9tzmPl5kO9PrsT0CyjM3pAD2\nu9YSlxoMCYQP5DCTafej0YkA/E8psNXAA/JjoqSPeZWGL2P7tUk+S/d4c7m/Q91e\n5A9f2LAxIOxBUZzpLgT1+lXi7uptEJA5KuVdEcmhyTiqFpdS658YvIlYhNmo5zCO\n68pQoVOlbwKBgQD2SmuxH9TmWyIH17Orqkjhwe09ob5ytWsXmACZQVplujiXRyg+\nJOJmcIbMC2ryZg95oMuNZAYJzTVjjfI50r9IvysvIqy2DVpLUjv5ci9r2A5tYlxv\nD/W+IQLip2s10+jKpkwIxOu/Z11vx+KC1HRYgQ2vED512qVf2F+ePGpjkQKBgQCK\njNjFxL0MfgTrSoxVrkyvkDhbddfiM1CjlBaRwMWwDuZBs7+7s6XMMM4Y+R2EG5RW\nGcNvz/+ar272kTY8P6SYYw+09WjLVvLvMGV60X2r8gbVqGn7ZPttGhmR3l1Qi0Dh\n2AjvTMy29h43HPYAVujECFLYkVcoOGNvYy9yq2kqHwKBgQCKY9Zyze4AMknWfR5F\nJLHCt3attpDKQaslITR6sebK4bgQrZ30uFpdmFq2ElV77BAWIMxJHyQNPdk2CsxO\nI5UOQgyR5RW0dmkgW4cdwI0Ptjcn7ErZ17AV7DM+QHQQg1PHgj7YR9+Lbt+VT+5m\nVYEBw5riI098dz7vUyClqpYE9A==\n-----END PRIVATE KEY-----\n".replace(/\\n/g, '\n'),
  scopes: ["https://www.googleapis.com/auth/spreadsheets"],
});

// Add headers before the routes are defined
app.use(function (req, res, next) {
  // Website you wish to allow to connect
  res.setHeader(
    "Access-Control-Allow-Origin",
    "https://opac17-6be3ebc1c395.herokuapp.com/"
  );

  // Request methods you wish to allow
  res.setHeader(
    "Access-Control-Allow-Methods",
    "GET, POST, OPTIONS, PUT, PATCH, DELETE"
  );

  // Request headers you wish to allow
  res.setHeader(
    "Access-Control-Allow-Headers",
    "X-Requested-With,content-type"
  );

  // Set to true if you need the website to include cookies in the requests sent
  // to the API (e.g. in case you use sessions)
  res.setHeader("Access-Control-Allow-Credentials", true);

  // Pass to next layer of middleware
  next();
});

app.get("/", function (req, res) {
  res.send("Node Server is running. Yay!!");
});

app.get("/fetchData", async function (req, res) {
  const doc = new GoogleSpreadsheet(
    "1JqgaUiFTSRuDrRiqA9LL_xynEfwaFSxtlrs0zYwgHWE",
    serviceAccountAuth
  );

  await doc.loadInfo(); // loads document properties and worksheets

  const sheet = doc.sheetsByIndex[0]; // or use `doc.sheetsById[id]` or `doc.sheetsByTitle[title]`
  const rows = await sheet.getRows();

  res.setHeader("Content-Type", "application/json");

  if (!rows) return res.json({ message: "No data found" }).status(404);
  // Website you wish to allow to connect
  res.status(200).json(rows.map((row) => row._rawData));
  return 0;
});

app.listen(process.env.PORT || 5000);
